<table border=0 style="background-color: #fff; padding: 5px;" cellspacing=0>
  <tr><td>
  <img src="http://groups.google.com/intl/en/images/logos/groups_logo_sm.gif"
         height=30 width=140 alt="Google Groups">
  </td></tr>
  <tr><td style="padding-left: 5px">
  <b>Inscreva-se em Armazém dos Orgânicos</b>
  </td></tr>
  <form action="http://groups.google.com/group/armazem-dos-organicos/boxsubscribe">
  <tr><td style="padding-left: 5px;">
  Email: <input type=text name=email>
  <input type=submit name="sub" value="Inscrever-me">
  </td></tr>
</form>
<tr><td align=right>
  <a href="http://groups.google.com/group/armazem-dos-organicos">Visitar o Grupo</a>
</td></tr>
</table>