<div id="sidebar">
    <div id="noticias">
        <h2>Notícias</h2>
        <ul id="listaNoticias">
            <?php foreach($this->noticias AS $noticia){ ?>
            <li><a href="noticia/<?php echo $noticia['slug']; ?>" title="<?php echo $noticia['titulo']; ?>"><?php echo $noticia['titulo']; ?></a></li>
            <?php } ?>
        </ul>
    </div>
    <div id="enquete">
        <h2>Enquete</h2>
        <a href="/enquete">Você teria interesse de<br/> comprar produtos<br/> orgânicos pela<br/> <b>internet?</b></a>
    </div>
</div>
<h2>O Armazém</h2>
<p>A busca por uma vida saudável, o convívio de forma harmoniosa com todas as formas de vida e sua preservação fez nascer na Família Franco e Batistelo, o desejo de transformar os sonhos em realidade. Motivados pelo amor e respeito à vida, não demorou a surgir o sonho de fazer acontecer.</p>
<p>Inicialmente um sítio com 21 ha de terra adquirido a 3 anos onde a natureza é completamente preservada, 10 ha de mata nativa e 11 ha de solo para cultivo, esta voltando a ter vida , através do cultivo e manejo ecológico que visa a produção sem o uso de agrotóxicos , adubos químicos e outras substâncias tóxicas e sintéticas , a idéia é evitar a contaminação dos alimentos ou do meio ambiente.</p>
<p>A dificuldade de encontrar produtos certificados e de qualidade fez surgir o Armazém dos Orgânicos é parte desse sonho, onde o acesso a qualidade de vida e produtos seguramente livres de agrotóxico poderão chegar a mesa de todos os que prezam pela vida saudável.</p>