<h2>Mídias</h2>
<div id="slideshow">
    <ul>
        <li><a href="images/midias/armazem-dos-organicos.jpg" title="Midia Armazém dos Orgânicos" >
                <img src="images/midias/thumbs/armazem-dos-organicos.jpg" alt="Midia Armazém dos Orgânicos" />
                Fonte: Jornal Serra Nossa
            </a></li>
        <li><a href="images/midias/armazem-dos-organicos-289-ed.jpg" title="Midia Armazém dos Orgânicos" >
                <img src="images/midias/thumbs/armazem-dos-organicos-289-ed.jpg" alt="Midia Armazém dos Orgânicos" />
                Fonte: Jornal Serra Nossa - Ed 289
            </a></li>
        <li><a href="images/midias/armazem-dos-organicos-292-ed.jpg" title="Midia Armazém dos Orgânicos" >
                <img src="images/midias/thumbs/armazem-dos-organicos-292-ed.jpg" alt="Midia Armazém dos Orgânicos" />
                Fonte: Jornal Serra Nossa - Ed 292
            </a></li>
        <li><a href="images/midias/armazem-dos-organicos-295-ed.jpg" title="Midia Armazém dos Orgânicos" >
                <img src="images/midias/thumbs/armazem-dos-organicos-295-ed.jpg" alt="Midia Armazém dos Orgânicos" />
                Fonte: Jornal Serra Nossa - Ed 295
            </a></li>
        <li><a href="images/midias/armazem-dos-organicos-297-ed.jpg" title="Midia Armazém dos Orgânicos" >
                <img src="images/midias/thumbs/armazem-dos-organicos-297-ed.jpg" alt="Midia Armazém dos Orgânicos" />
                Fonte: Jornal Serra Nossa - Ed 297
            </a></li>
    </ul>
    <p class="legenda">*Clique nas imagens para ampliar</p>
</div>
<script type="text/javascript">
    $(function() {
        $('#slideshow a').lightBox({
            fixedNavigation:true,
            txtImage: 'Imagem',
            txtOf: 'de'
        });
    });
</script>