<h2>EMPRESA</h2>
<p>A busca por uma vida saudável, o convívio de forma harmoniosa com todas as formas de vida e sua preservação fez nascer na Família Franco e Batistelo, o desejo de transformar os sonhos em realidade. Motivados pelo amor e respeito à vida, não demorou a surgir o sonho de fazer acontecer.</p>
<p>Inicialmente um sítio com 21 ha de terra adquirido a 3 anos onde a natureza é completamente preservada, 10 ha de mata nativa e 11 ha de solo para cultivo, esta voltando a ter vida , através do cultivo e manejo ecológico que visa a produção sem o uso de agrotóxicos , adubos químicos e outras substâncias tóxicas e sintéticas , a idéia é evitar a contaminação dos alimentos ou do meio ambiente.</p>
<p>A dificuldade de encontrar produtos certificados e de qualidade fez surgir o Armazém dos Orgânicos é parte desse sonho, onde o acesso a qualidade de vida e produtos seguramente livres de agrotóxico poderão chegar a mesa de todos os que prezam pela vida saudável.</p>
<h2>PRODUTOS</h2>
<p>Mais que vender produtos orgânicos o Armazém dos Orgânicos promove qualidade de vida , saúde e sustentabilidade . Todos os nosso produtos possuem certificação orgânica o que garante a  credibilidade de nossos produtos.</p>
<h2>Fornecedores</h2>
<p>Nossos fornecedores são produtores rurais que vendem seu produto diretamente ou através de associações e cooperativas ou o próprio produtor individual que constitui uma  empresa particular que cultivam, e industrializam  seus produto , e que da mesma forma  respeitam todas as normas de legislação nacional de produção orgânica.</p>
